project:
  type: website
  output-dir: docs

website:
  title: "coreR Test Course: 2024-01-01 - 2024-12-31"
  ### NEW subtitle removed - doesn't work for website
  reader-mode: false
  repo-url: https://github.com/nceas-learning-hub/coreR_test
  favicon: logo-lh.png # learning hub logo
  bread-crumbs: false ### NEW keep header clean
  navbar: ### NEW inspired by Nick's site
    right:
      - text: "Instructors"
        menu:
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
      - icon: github
        href: https://github.com/nceas-learning-hub/coreR_test
        aria-label: GitHub
  sidebar:
    title: "Training Materials"
    style: "docked"
      ### "docked" separates the side bar, with contrast bg; "floating" appears similar to rest of page
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/nceas-learning-hub/coreR_test
    contents:
      - index.qmd
      - section: "Day 1"
        contents:
        - s01_r_programming_introduction.qmd  ###  (coreRlessons v0.1.0)
        - s02_r_quarto_literate_analysis.qmd  ###  (coreRlessons v0.1.0)
        - s03_activity_reproducibility_lego.qmd  ###  (coreRlessons v0.1.0)
      - section: "Day 2"
        contents:
        - s04_github_introduction.qmd  ###  (coreRlessons v0.1.0)
        - s05_lecture_tidy_data.qmd  ###  (coreRlessons v0.1.0)
        - s06_r_tidyverse_clean_wrangle.qmd  ###  (coreRlessons v0.1.0)
        # - s07_r_practice_tidy_data_joins.qmd  ###  (coreRlessons v0.1.0)
      - section: "Day 3"
        contents:
        - s08_github_collaboration.qmd  ###  (coreRlessons v0.1.0)
      - section: "Day 4"
        contents:
        - s09_r_functions.qmd  ###  (coreRlessons v0.1.0)
        - s10_r_packages.qmd  ###  (coreRlessons v0.1.0)
  page-footer:
    center: "Copyright \u00a9 2024, NCEAS"
    background: "#0C4537"

bibliography: book.bib

format:
  html:
    theme:
       light: _extensions/nceas-learning-hub/lh_theme/lh_light.scss
       dark: _extensions/nceas-learning-hub/lh_theme/lh_dark.scss
    css: lh-style.css   ### doesn't render NCEAS logo if put in scss file?
    toc: true
    number-sections: true
    title-block-banner: "blue" ### need this here to "turn on" the title-block-banner

filters:
- courseformat

editor: source
